// Define ENDPOINT 
export const BASE_ENDPOINT = "/api";

export const SERVER_STATUS_ENDPOINT = BASE_ENDPOINT + "/server-status";

export const BOOKMARKS_ENDPOINT_BASE = BASE_ENDPOINT + "/bookmarks";

export const BOOKMARKS_ENDPOINT_ADD = BOOKMARKS_ENDPOINT_BASE + "/add";

export const BOOKMARKS_ENDPOINT_UPDATE = BOOKMARKS_ENDPOINT_BASE + "/update";

export const BOOKMARKS_ENDPOINT_DELETE = BOOKMARKS_ENDPOINT_BASE + "/delete/:id";

export const BOOKMARKS_ENDPOINT_GETBYTAG = BOOKMARKS_ENDPOINT_BASE + "/bytag/:tag";

export const BOOKMARKS_ENDPOINT_GETBYID = BOOKMARKS_ENDPOINT_BASE + "/:id";

export const BOOKMARKS_ENDPOINT_GETBYDATE = BOOKMARKS_ENDPOINT_BASE + "/bydate/:date";

export const BOOKMARKS_ENDPOINT_SEARCH = BOOKMARKS_ENDPOINT_BASE + "/search/:query";

export const BOOKMARKS_ENDPOINT_FILTER = BOOKMARKS_ENDPOINT_BASE + "/filter";

export const TAGS_ENDPOINT_BASE = BASE_ENDPOINT + "/tags";

export const TAGS_ENDPOINT_SEARCH = TAGS_ENDPOINT_BASE + "/search/:substring";

export const DATES_ENDPOINT_BASE = BASE_ENDPOINT + "/dates";

export const DATES_ENDPOINT_RANGE = DATES_ENDPOINT_BASE + "/range/:date_start/:date_end";

export const COMMENTS_ENDPOINT_BASE = BASE_ENDPOINT + "/comments";

export const COMMENTS_ENDPOINT_ADD = COMMENTS_ENDPOINT_BASE + "/add";

export const COMMENTS_ENDPOINT_UPDATE = COMMENTS_ENDPOINT_BASE + "/update";

export const COMMENTS_ENDPOINT_DELETE = COMMENTS_ENDPOINT_BASE + "/delete/:id";

export const COMMENTS_ENDPOINT_GETBYID = BOOKMARKS_ENDPOINT_BASE + "/:id";

export const COMMENTS_ENDPOINT_LISTBYBOOKMARKID = BOOKMARKS_ENDPOINT_GETBYID + "/comments";

export const URLS_ENDPOINT_BASE = BASE_ENDPOINT + "/urls";

export const URLS_ENDPOINT_TITLE = URLS_ENDPOINT_BASE + "/title";

// Users

export const USERS_ENDPOINT_BASE = BASE_ENDPOINT + "/users";

export const USERS_ENDPOINT_LIST = USERS_ENDPOINT_BASE + "/";

export const USERS_ENDPOINT_ADD = USERS_ENDPOINT_BASE + "/add";

export const USERS_ENDPOINT_EDIT = USERS_ENDPOINT_BASE + "/edit";

export const USERS_ENDPOINT_DELETE = USERS_ENDPOINT_BASE + "/delete";

export const USERS_ENDPOINT_GETBYID = USERS_ENDPOINT_BASE + "/:id";

// Roles

export const ROLES_ENDPOINT_BASE = BASE_ENDPOINT + "/roles";

export const ROLES_ENDPOINT_LIST = ROLES_ENDPOINT_BASE + "/";

export const ROLES_ENDPOINT_ADD = ROLES_ENDPOINT_BASE + "/add";

export const ROLES_ENDPOINT_EDIT = ROLES_ENDPOINT_BASE + "/edit";

export const ROLES_ENDPOINT_DELETE = ROLES_ENDPOINT_BASE + "/delete";

export const ROLES_ENDPOINT_GETBYID = ROLES_ENDPOINT_BASE + "/:id";
